import test from 'node:test';
import assert from 'node:assert/strict';
import { tokenize,keywordDetails,normalize,cosine,teachingEmbedding,rank,chunkDocument,buildAnswer,validateCitation,canonicalURL,createCrawler,crawlStep,indexedDocuments,metrics,benchmark } from '../src/engine.js';
import { DOCUMENTS,CRAWL_EXTRA,WEB_PAGES,BENCHMARK,CONCEPTS,AUDIT } from '../src/data.js';
import { DAYS,GLOSSARY,SOURCES } from '../src/course.js';
const d={id:'test',title:'Neural learning',body:'Neural networks learn. Neural networks learn.'};
const approx=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('tokenizer lowercases and removes punctuation / stopwords',()=>assert.deepEqual(tokenize('How do NEURAL networks learn?'),['neural','networks','learn']));
test('stopwords can be preserved',()=>assert.deepEqual(tokenize('How do we learn?',false),['how','do','we','learn']));
test('unicode letters do not crash word splitting',()=>assert.deepEqual(tokenize('café Привет 123'),['café','привет','123']));
test('empty and punctuation-only input has no tokens',()=>assert.deepEqual(tokenize('  !? '),[]));
test('counts are real title and body occurrences',()=>assert.equal(keywordDetails('neural networks learn',d).score,7));
test('repeated query terms are deduplicated',()=>assert.equal(keywordDetails('neural neural',d).score,3));
test('title weighting is applied separately',()=>assert.equal(keywordDetails('neural',d,{titleWeight:3}).score,5));
test('no implicit stemming',()=>assert.equal(keywordDetails('learning',{...d,title:'learn',body:'learn'}).score,0));
test('normalizing a zero vector returns zeros',()=>assert.deepEqual(normalize([0,0]),[0,0]));
test('normalization gives unit length',()=>approx(Math.hypot(...normalize([3,4])),1));
test('cosine same, orthogonal, and opposite directions',()=>{approx(cosine([1,0],[2,0]),1);approx(cosine([1,0],[0,1]),0);approx(cosine([1,0],[-2,0]),-1);});
test('cosine of zero vectors is handled',()=>assert.equal(cosine([0,0],[1,2]),0));
test('mismatched vectors are rejected',()=>assert.throws(()=>cosine([1],[1,2]),TypeError));
test('non-finite vectors are rejected',()=>assert.throws(()=>cosine([NaN],[1]),TypeError));
test('teaching vectors have eight dimensions',()=>assert.equal(teachingEmbedding('garlic dinner').length,CONCEPTS.length));
test('unknown vocabulary maps to zero, not fabricated meaning',()=>assert.ok(teachingEmbedding('zqxv wobblesnark').every(x=>x===0)));
test('query and documents with different words can activate same concept',()=>approx(cosine(teachingEmbedding('computers learn'),teachingEmbedding('models training')),1));
test('no results for empty queries in every mode',()=>{for(const mode of ['keyword','semantic','hybrid','rrf'])assert.deepEqual(rank('',DOCUMENTS,{mode}),[]);});
test('no results for stopword-only queries',()=>assert.deepEqual(rank('how do we',DOCUMENTS),[]));
test('no lexical match to machine-learning page in stated failure example',()=>assert.ok(!rank('how do computers learn',DOCUMENTS,{mode:'keyword'}).some(x=>x.doc.id==='ml')));
test('teaching semantic search retrieves the machine-learning page',()=>assert.ok(rank('how do computers learn',DOCUMENTS,{mode:'semantic'}).some(x=>x.doc.id==='ml')));
test('keyword results rank by decreasing score',()=>{const r=rank('neural networks',DOCUMENTS,{mode:'keyword'});assert.equal(r[0].doc.id,'neural');assert.ok(r.every((x,i)=>!i||r[i-1].score>=x.score));});
test('hybrid alpha endpoints preserve each signal’s order',()=>{const q='garlic pasta';assert.deepEqual(rank(q,DOCUMENTS,{mode:'hybrid',alpha:1}).map(r=>r.doc.id),rank(q,DOCUMENTS,{mode:'keyword'}).map(r=>r.doc.id));assert.deepEqual(rank(q,DOCUMENTS,{mode:'hybrid',alpha:0}).map(r=>r.doc.id),rank(q,DOCUMENTS,{mode:'semantic'}).map(r=>r.doc.id));});
test('hybrid score is exactly its displayed contributions',()=>{for(const r of rank('neural networks',DOCUMENTS,{alpha:.25}))approx(r.score,.25*r.keywordNormalized+.75*r.semantic);});
test('zero keyword maximum does not cause NaN',()=>assert.ok(rank('computers',DOCUMENTS).every(x=>Number.isFinite(x.score))));
test('RRF is finite and deterministic',()=>{const a=rank('garlic dinner',DOCUMENTS,{mode:'rrf'}),b=rank('garlic dinner',DOCUMENTS,{mode:'rrf'});assert.deepEqual(a,b);assert.ok(a.every(x=>Number.isFinite(x.score)&&x.score>0));});
test('neural adapter vectors can be supplied without teaching dimensions',()=>{const docs=[{id:'a',title:'alpha',body:'text'},{id:'b',title:'beta',body:'text'}];const rows=rank('query',docs,{mode:'semantic',queryVector:[1,0,0],vectors:new Map([['a',[1,0,0]],['b',[0,1,0]]])});assert.equal(rows[0].doc.id,'a');});
test('all sentence offsets reconstruct exact source passages',()=>{for(const doc of DOCUMENTS)for(const p of chunkDocument(doc))assert.equal(doc.body.slice(p.start,p.end),p.text);});
test('chunk IDs are unique',()=>{const ids=DOCUMENTS.flatMap(chunkDocument).map(p=>p.id);assert.equal(new Set(ids).size,ids.length);});
test('extractive answer has valid quotes from real local sources',()=>{const a=buildAnswer('neural networks learn');assert.equal(a.abstained,false);assert.ok(a.passages.length<=3);assert.ok(a.passages.every(p=>validateCitation(p)));assert.ok(a.passages.every(p=>a.text.includes(p.text)));});
test('answer without context abstains',()=>assert.equal(buildAnswer('neural networks',DOCUMENTS,{withContext:false}).abstained,true));
test('unsupported query abstains',()=>assert.equal(buildAnswer('orbital zirconium flux capacitor').abstained,true));
test('character budget is obeyed',()=>assert.ok(buildAnswer('neural networks',DOCUMENTS,{charBudget:100}).passages.reduce((s,p)=>s+p.text.length,0)<=100));
test('a changed quote is not a valid citation',()=>{const p=chunkDocument(DOCUMENTS[0])[0];assert.equal(validateCitation({...p,text:p.text+' invented'}),false);});
test('bad citation offsets and unknown docs fail',()=>{const p=chunkDocument(DOCUMENTS[0])[0];assert.equal(validateCitation({...p,start:-1}),false);assert.equal(validateCitation({...p,docId:'absent'}),false);});
test('URL canonicalization strips fragments',()=>assert.equal(canonicalURL('/neural#weights'),'https://byte.test/neural'));
test('javascript and non-HTTPS URLs are rejected',()=>{assert.equal(canonicalURL('javascript:alert(1)'),null);assert.equal(canonicalURL('http://byte.test/'),null);});
test('one crawl step reads the hub and queues links',()=>{const c=crawlStep(createCrawler());assert.equal(c.indexed.length,0);assert.equal(c.seen[0],'https://byte.test/');assert.ok(c.queue.length>1);});
test('crawl steps do not mutate previous state',()=>{const c=createCrawler(),copy=structuredClone(c);crawlStep(c);assert.deepEqual(c,copy);});
function fullCrawl(limit=12){let c=createCrawler(limit),steps=0;while(!c.done&&steps++<100)c=crawlStep(c);assert.ok(steps<100);return c;}
test('crawler terminates despite cyclic links',()=>assert.equal(fullCrawl().done,true));
test('crawler reports blocks, duplicates, and missing pages',()=>{const statuses=fullCrawl().log.map(x=>x.status);for(const s of ['visited','blocked','skip','missing'])assert.ok(statuses.includes(s));});
test('crawler never indexes the private or external pages',()=>{const c=fullCrawl();assert.ok(!c.indexed.includes('private'));assert.equal(new Set(c.indexed).size,c.indexed.length);});
test('crawler honors document cap',()=>assert.equal(fullCrawl(3).indexed.length,3));
test('crawler can discover both new teaching documents',()=>{const docs=indexedDocuments(fullCrawl().indexed);for(const d of CRAWL_EXTRA)assert.ok(docs.some(x=>x.id===d.id));});
test('precision, recall, and reciprocal rank match hand calculations',()=>{const m=metrics(['x','a','b','c'],['a','b'],3);approx(m.precision,2/3);approx(m.recall,1);approx(m.reciprocalRank,.5);});
test('empty slots count against precision@3',()=>approx(metrics(['a'],['a'],3).precision,1/3));
test('out-of-collection queries have no recall and can abstain',()=>{const m=metrics([],[],3);assert.equal(m.recall,null);assert.equal(m.abstained,true);});
test('invalid k is rejected',()=>assert.throws(()=>metrics([],[],0),TypeError));
test('benchmark covers all three algorithms and eight queries',()=>{const b=benchmark();assert.equal(b.length,3);assert.ok(b.every(r=>r.rows.length===BENCHMARK.length));});
test('benchmark metrics are bounded',()=>{for(const r of benchmark())for(const key of ['precision','recall','mrr','abstention'])assert.ok(r[key]>=0&&r[key]<=1);});
test('curriculum has seven complete days and 21 explained checks',()=>{assert.deepEqual(DAYS.map(d=>d.id),[1,2,3,4,5,6,7]);for(const d of DAYS){assert.equal(d.sections.length,3);assert.equal(d.quiz.length,3);assert.ok(d.code.length>100);assert.equal(d.mission.length,3);for(const q of d.quiz){assert.equal(q.choices.length,3);assert.ok(q.answer>=0&&q.answer<3);assert.ok(q.why.length>30);}for(const ref of d.refs)assert.ok(SOURCES[ref]);}});
test('all document IDs and benchmark labels resolve',()=>{const ids=DOCUMENTS.map(d=>d.id);assert.equal(new Set(ids).size,ids.length);for(const b of BENCHMARK)for(const id of b.relevant)assert.ok(ids.includes(id));for(const a of AUDIT)assert.ok(ids.includes(a.source));for(const p of WEB_PAGES)if(p.docId)assert.ok([...DOCUMENTS,...CRAWL_EXTRA].some(d=>d.id===p.docId));});
test('glossary includes the major concepts',()=>{assert.ok(GLOSSARY.some(x=>x[0]==='Embedding'));assert.ok(GLOSSARY.some(x=>x[0]==='MRR'));});
