/** Course narration is original instructional expansion of the seven-day plan.
 * Day 1 follows the supplied script; Days 2–7 follow the plan in the conversation.
 */
export const SOURCES = {
  ir: { name: 'Introduction to Information Retrieval · Stanford', url: 'https://nlp.stanford.edu/IR-book/' },
  embeddings: { name: 'Semantic search · Sentence Transformers', url: 'https://sbert.net/examples/sentence_transformer/applications/semantic-search/README.html' },
  rrf: { name: 'Reciprocal rank fusion · Elastic', url: 'https://www.elastic.co/docs/reference/elasticsearch/rest-apis/reciprocal-rank-fusion' },
  robots: { name: 'Robots Exclusion Protocol · RFC 9309', url: 'https://www.rfc-editor.org/rfc/rfc9309.html' },
  cors: { name: 'Cross-Origin Resource Sharing · MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS' },
  rag: { name: 'Retrieval-Augmented Generation · Lewis et al.', url: 'https://arxiv.org/abs/2005.11401' },
  metrics: { name: 'Evaluating ranked retrieval · Stanford', url: 'https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-ranked-retrieval-results-1.html' },
  neural: { name: 'Pretrained feature extraction · Transformers.js', url: 'https://huggingface.co/docs/transformers.js/en/pipelines' }
};
export const DAYS = [
  {
    id: 1, name: 'Make it search', subtitle: 'Words in. Useful pages out.', color: 'yellow', icon: 'search', time: '15–20 min', category: 'THE FOUNDATION',
    summary: 'Build a tiny internet, split a query into words, and give every page a score.',
    intro: 'Let’s build an AI search engine from scratch. Before it can write answers or understand what we mean, it needs to do something much simpler: find information. Today we start with a tiny collection of pages, so we can actually see what happens between typing a question and getting a result.',
    sections: [
      { title: 'First, give it something to search.', text: 'Our tiny internet is a collection of documents, and every document has a title, a body, and a URL. That is enough to search the text and show a useful result. Open the collection in the lab and you will find pages about neural networks, Python, recipes, and a few unrelated topics. They are deliberately short: you should be able to look at a page and work out why it did or did not match.', detail: 'These are original teaching documents, not pages fetched from the live web. Their .test addresses are identifiers for our local examples. Searching this collection is not the same as searching the entire internet.' },
      { title: 'Turn a question into something we can count.', text: 'When someone types “How do neural networks learn?”, we lowercase the query and split it into words. Then we can remove common words such as “how” and “do”, leaving “neural”, “networks”, and “learn”. We apply the same basic word splitting to each document, count exact matches, and add those counts together. In this first version, each occurrence contributes one point; the lab also lets you experiment with giving title matches extra weight.', detail: 'This tokenizer does not stem words, recognize phrases, or understand context. “Learn” and “learning” are different tokens. A repeated query word is counted once, so typing the same word ten times does not quietly change its weight. Stopword removal is optional because common words can matter in some searches.' },
      { title: 'Let the scores decide the order.', text: 'Once every page has a score, we sort from highest to lowest and display the matches. Try “neural networks”, inspect the top result, and count the highlighted words yourself. Then change the query to “how do computers learn”. The article called “Introduction to machine learning” has useful information, but its title and body do not contain either “computers” or “learn”. Our literal matcher misses it, even though a person can connect those ideas.', detail: 'Counting words is a baseline, not a production relevance model. Long or repetitive pages can collect more points without being better answers. Later versions can use term rarity, length normalization, phrase matching, and other signals. Today the goal is to understand the complete path from input to sorted results.' }
    ],
    takeaway: 'A relevance score is a rule we define, not something the computer magically knows.',
    mission: ['Search “how do neural networks learn?” and inspect the matching words.', 'Try “how do computers learn” and notice which useful page is missing.', 'Change title weight or stopwords and predict the effect before you search again.'],
    bridge: 'Tomorrow, we keep the documents but change how we represent them, so different wording can still lead to a useful match.',
    codeTitle: 'A small, inspectable word matcher',
    code: `import { DOCUMENTS } from './src/data.js';\nimport { rank } from './src/engine.js';\n\nconst query = 'how do neural networks learn?';\nconst hits = rank(query, DOCUMENTS, {\n  mode: 'keyword',\n  titleWeight: 1,\n  removeStopwords: true\n});\n\nfor (const { doc, score, counts } of hits) {\n  console.log(doc.title, score);\n  console.table(counts);\n}`,
    codeNote: 'Run this in a module at the repository root, or try the equivalent command-line example. The actual tokenizer and scoring loop live in src/engine.js.',
    refs: ['ir'],
    quiz: [
      { q: 'Our query is “learn”. A page contains only “learning”. What happens in Day 1?', choices: ['They automatically match.', 'They do not match as exact tokens.', 'The page gets half a point.'], answer: 1, why: 'Our first tokenizer does not reduce words to a stem. It compares the exact lowercase tokens.' },
      { q: 'Why do we sort the scores?', choices: ['To put stronger matches before weaker ones.', 'To prove the highest result is true.', 'To change the text in every page.'], answer: 0, why: 'Sorting determines the display order. A high match score says nothing by itself about truth.' },
      { q: 'Why can an excellent machine-learning article get a zero?', choices: ['The internet has stopped working.', 'Its URL must be too short.', 'It expresses the idea using different words.'], answer: 2, why: 'A lexical mismatch can hide a relevant article. That is the problem we explore next.' }
    ]
  },
  {
    id: 2, name: 'Search by meaning', subtitle: 'Different words. Related ideas.', color: 'pink', icon: 'spark', time: '20–25 min', category: 'THE REPRESENTATION',
    summary: 'Make text numerical, compare vectors, and see why meaning is more than a word match.',
    intro: 'Our search engine can find matching words, but it misses relationships that feel obvious to us. Today, let’s give each query and document a numerical representation, so we can compare what they are about even when they use different wording. The important change is not the search bar; it is the thing we compare behind it.',
    sections: [
      { title: 'An embedding is a list of coordinates.', text: 'Imagine describing a piece of text with numbers instead of keeping it only as a string of words. That list of numbers is a vector. With a trained text-embedding model, related text can receive similar vectors, which gives us a practical way to retrieve pages by semantic similarity. We create document vectors ahead of time, create a query vector when someone searches, and compare them in the same representation space.', detail: 'In the default lab, we use eight human-written concept axes so the coordinates are visible and understandable. This is an illustrative vocabulary model, not a trained neural embedding model. The optional MiniLM button downloads a real pretrained model and runs inference in your browser. It is not trained from scratch here.' },
      { title: 'Compare directions, not just shared words.', text: 'Cosine similarity measures how closely two vectors point in the same direction. We multiply corresponding coordinates, add those products, and divide by the lengths of the two vectors. Normalization makes each nonzero vector have length one; the dot product then equals cosine similarity. If a vector is all zeros, our implementation returns zero rather than dividing by zero.', detail: 'Cosine similarity ranges from −1 to 1 in general. Our nonnegative teaching vectors produce values between 0 and 1. A similarity of 0.8 is not an 80% probability that the result is correct. The two-axis picture shows only a slice of the eight-dimensional teaching space; ranking uses all eight dimensions.' },
      { title: 'Same topic is not always the same answer.', text: 'Search “how do computers learn” again and inspect the machine-learning article. In teaching mode, those words activate the learning axis, as do the article’s words about models and training. That is why the page can now be retrieved without exact matches. But a broad topic match can also bring back a page that does not answer the specific question. Try a very precise query, and watch how much detail this small representation throws away.', detail: 'Real models also need evaluation, especially for short queries and longer documents. They can struggle with negation, unusual names, domain-specific terms, and ambiguity. Use the same compatible model for queries and documents; vectors from unrelated models do not share a meaningful coordinate system.' }
    ],
    takeaway: 'Changing the representation changes what the search engine can recognize.',
    mission: ['Search “how do computers learn” in teaching mode.', 'Inspect the coordinates and compare the top two similarity scores.', 'Try an unfamiliar phrase; notice the limits of a tiny vocabulary. The neural download is optional.'],
    bridge: 'We do not have to throw away exact words to use meaning. Tomorrow, we combine both signals.',
    codeTitle: 'Cosine similarity, without a black box',
    code: `function cosine(a, b) {\n  if (a.length !== b.length) {\n    throw new Error('Dimensions must match');\n  }\n  const dot = a.reduce((sum, x, i) => sum + x * b[i], 0);\n  const lengths = Math.hypot(...a) * Math.hypot(...b);\n  return lengths ? dot / lengths : 0;\n}\n\ncosine([1, 0], [1, 0]); // 1: same direction\ncosine([1, 0], [0, 1]); // 0: perpendicular\ncosine([1, 0], [-1, 0]); // -1: opposite`,
    codeNote: 'src/neural.js contains the optional pretrained feature-extraction adapter. No model or credentials are downloaded until you choose to load it.',
    refs: ['embeddings','neural'],
    quiz: [
      { q: 'Why embed both documents and the query with compatible representations?', choices: ['So both can be compared in the same vector space.', 'So every document gets the same vector.', 'So we can delete the original text.'], answer: 0, why: 'The coordinates must have compatible meaning for vector comparisons to be useful. Keep the original text for results and evidence.' },
      { q: 'A cosine similarity of 0.8 means…', choices: ['The source is 80% accurate.', 'Their vector directions are quite similar.', 'The document contains eight query words.'], answer: 1, why: 'Cosine measures a geometric relationship, not a calibrated probability of correctness.' },
      { q: 'What is the default eight-axis lab model?', choices: ['An LLM trained on the entire web.', 'A perfect semantic search engine.', 'A hand-written teaching representation.'], answer: 2, why: 'The default deliberately exposes the mechanics. The optional neural mode is separately labeled.' }
    ]
  },
  {
    id: 3, name: 'Rank the good stuff', subtitle: 'Two signals are better to investigate.', color: 'lavender', icon: 'bars', time: '15–20 min', category: 'THE RANKING',
    summary: 'Mix exact matches with meaning, move the slider, and watch the result order change.',
    intro: 'At this point, we have two different ways of deciding whether a page matters: it can contain the exact words we searched for, or it can describe a similar idea. Neither one is automatically best. Today, let’s combine them and make the tradeoff visible instead of burying it inside a scoring function.',
    sections: [
      { title: 'Keep the signal that matters for the query.', text: 'For “Python list comprehension”, the exact terms are useful. For “a shorter way to write a loop”, we may want the same article even though the wording changes. A hybrid ranker lets a page earn points from both literal matching and semantic similarity. It does not guarantee a better result for every query, but it gives us a balance we can inspect and test.', detail: 'This lab uses the same transparent teaching vectors as Day 2, not any optional neural model you loaded there. Keeping a fixed representation makes the ranking experiment reproducible and offline. Production systems might also rerank a short candidate list with a second model.' },
      { title: 'Put the scores on comparable scales.', text: 'A keyword count might be 12 while a cosine similarity is 0.75, so adding them directly would quietly let the count dominate. Here, we divide each keyword score by the largest keyword score for that query. That places the normalized lexical values between zero and one. We can then choose a weight α and compute α × keyword + (1 − α) × similarity for each page.', detail: 'If every keyword score is zero, the normalized values remain zero. Query-wise maximum normalization is an educational choice, not the only method. Raw weighted addition does not calibrate scores as probabilities. The RRF option is an alternative that combines positions in separate result lists rather than their raw scores.' },
      { title: 'Make a prediction, then touch the slider.', text: 'Move the slider all the way toward exact words, inspect the top three results, and then move toward meaning. Each result shows its two contributions, so you can tell why it moved rather than only noticing that it did. Try the precise and conversational versions of the Python query. Keep a note of one change you expect to help, because on Day 7 we will test assumptions across more than one favorite example.', detail: 'Changing the weight based on a handful of examples can overfit those examples. In a larger project, keep separate development queries for tuning and held-out queries for evaluation. A small score change can swap two nearly tied results without meaningfully changing answer quality.' }
    ],
    takeaway: 'A ranking system is a collection of explicit decisions about which signals to trust.',
    mission: ['Compare “Python list comprehension” with “a shorter way to write a loop”.', 'Move the exact-word weight to 0%, 50%, and 100%.', 'Inspect a score breakdown, then compare the RRF alternative.'],
    bridge: 'Better ranking cannot find a page that is missing from our collection. Tomorrow, we build the discovery step.',
    codeTitle: 'A normalized hybrid score',
    code: `const largestCount = Math.max(0, ...rows.map(r => r.keyword));\nconst alpha = 0.5;\n\nfor (const row of rows) {\n  const keyword = largestCount ? row.keyword / largestCount : 0;\n  row.score = alpha * keyword\n            + (1 - alpha) * row.semantic;\n}\n\nrows.sort((a, b) => b.score - a.score);`,
    codeNote: 'The full rank() function also removes zero-score results and breaks ties consistently by document ID. The RRF option uses a rank constant of 60.',
    refs: ['ir','rrf'],
    quiz: [
      { q: 'Why normalize keyword counts before mixing them with cosine scores?', choices: ['To force the same page to win.', 'To make the numeric scales more comparable.', 'To convert the scores into truth probabilities.'], answer: 1, why: 'Different scales would make the mixing weight misleading. Normalization still does not establish truth.' },
      { q: 'With α = 1 in our weighted sum, which signal decides the order?', choices: ['Only the normalized keyword signal.', 'Only semantic similarity.', 'Both signals equally.'], answer: 0, why: 'The semantic contribution is multiplied by 1 − α, which becomes zero.' },
      { q: 'What does reciprocal rank fusion combine?', choices: ['URL lengths.', 'The average document text.', 'Positions in separate result lists.'], answer: 2, why: 'RRF uses reciprocal rank contributions rather than directly adding incomparable raw relevance scores.' }
    ]
  },
  {
    id: 4, name: 'Follow the links', subtitle: 'Give your tiny internet room to grow.', color: 'mint', icon: 'globe', time: '20–25 min', category: 'THE DISCOVERY',
    summary: 'Step through a crawler, inspect its queue, skip duplicates, and grow your index.',
    intro: 'So far, every page in our engine is something we have manually given it. Today, let’s build the idea that makes a collection grow: start on a page, save useful content, find the links, and visit the next page. We will follow that process one step at a time so it never feels like the crawler is magically discovering the web.',
    sections: [
      { title: 'A crawler needs a to-do list.', text: 'We begin with one starting URL in a queue. On each step, the crawler takes the first URL, checks it, reads the page, and adds its discovered links to the end of the queue. This breadth-first order explores nearby pages before moving farther away. The little website in the lab is a fixed local graph, which lets us watch exactly where each link leads without making any external requests.', detail: 'This is a simulation of crawling, not a crawler secretly browsing live sites. A static browser course cannot reliably fetch arbitrary sites because of browser security restrictions such as CORS. A real crawler normally runs on a server and needs network-level controls as well as page parsing.' },
      { title: 'Not every link deserves a visit.', text: 'Pages often link back to each other, so a seen set stops us from looping forever. We remove URL fragments so /neural and /neural#weights are treated as the same page in this example. The domain allowlist rejects links outside byte.test, the private page is blocked by our fixture’s robots rule, and a missing page becomes a recorded error rather than crashing the whole crawl.', detail: 'The fixture’s blocked flag illustrates the decision; it is not a complete robots.txt parser. Real crawlers must obey applicable access restrictions, respect robots policies, identify themselves, limit request rates, cap response sizes, and handle redirects and failures. Robots rules are not authentication and should not be used to protect secrets.' },
      { title: 'Discovery and search are different jobs.', text: 'When an allowed page contains a document, the crawler saves its identifier in the index. Ranking still happens later, when a user asks a question. Click “Use indexed pages” after discovering the two new teaching pages, and the playground will include them alongside the original collection. Now the index can grow without changing the basic search interface or scoring rules.', detail: 'A real index is a stored representation of previously collected content, not a live view of every site. Large systems also need content deduplication, refresh schedules, storage, inverted indexes, vector indexes, and deletion policies. We deliberately keep those outside today’s small, inspectable graph.' }
    ],
    takeaway: 'A crawler collects information. The ranker decides which of that information fits a query.',
    mission: ['Step through the first few URLs and watch the queue change.', 'Find a duplicate, an outside-domain link, and a blocked page in the log.', 'Run the crawl, then add its indexed pages to your playground.'],
    bridge: 'Now we can find relevant pages. Tomorrow, we use their passages to help answer a question.',
    codeTitle: 'Watch a complete local crawl',
    code: `import { createCrawler, crawlStep, indexedDocuments }\n  from './src/engine.js';\n\nlet crawler = createCrawler(12);\nwhile (!crawler.done) {\n  crawler = crawlStep(crawler);\n  console.log(crawler.log[0]);\n}\n\nconst collected = indexedDocuments(crawler.indexed);\nconsole.log(collected.map(page => page.title));`,
    codeNote: 'crawlStep() follows only the local graph in src/data.js. It does not issue HTTP requests or bypass anyone’s access controls.',
    refs: ['robots','cors'],
    quiz: [
      { q: 'What belongs in the crawler queue?', choices: ['The answer to the current question.', 'The model’s neural weights.', 'URLs waiting to be considered.'], answer: 2, why: 'The queue is the crawler’s to-do list. Each step removes one URL and may discover more.' },
      { q: 'Why maintain a seen set?', choices: ['To avoid visiting the same canonical URL repeatedly.', 'To make blocked pages public.', 'To assign relevance scores before a query exists.'], answer: 0, why: 'Links form cycles. A seen set prevents repeated visits from turning into an endless loop.' },
      { q: 'Does this lesson actually crawl public websites?', choices: ['Yes, the whole internet.', 'No, it steps through a clearly labeled local website simulation.', 'Only private websites.'], answer: 1, why: 'The local fixture makes the behavior reproducible, safe, and inspectable without a server.' }
    ]
  },
  {
    id: 5, name: 'From links to answers', subtitle: 'Give the answer something to stand on.', color: 'peach', icon: 'chat', time: '20–25 min', category: 'THE ANSWER',
    summary: 'Retrieve passages, assemble context, and see the structure of a grounded answer.',
    intro: 'Getting useful links is a big step, but it still leaves the reader to open every page and assemble the answer. Today, let’s connect retrieval to an answer step. The key idea is to find relevant source passages first, then give the answer-writing system that evidence instead of asking it to answer from nowhere.',
    sections: [
      { title: 'Retrieve before you write.', text: 'The pipeline starts with the same query and ranking system we already have. We select a small number of relevant documents, split them into passages, and keep the most useful text within a context budget. The user’s question and those passages can then become the input to a language model. This pattern is called retrieval-augmented generation, or RAG: retrieval supplies context, while generation writes an answer.', detail: 'The default course does not call an LLM. Our offline answer builder selects and copies source sentences so you can inspect the evidence path without an API key. It demonstrates retrieval and context assembly, not neural generation. The generated prompt is ready to inspect, and docs/EXTENDING.md explains the production boundary.' },
      { title: 'Bring enough context, not every page.', text: 'Open the evidence tray and change how many documents we retrieve. A passage may contain the answer, but a short snippet can also lose a definition or qualification. Keeping passage IDs, document IDs, and character offsets lets us trace each selected sentence back to its exact location. In this demo, the context budget is measured in characters; a real model needs its own token accounting.', detail: 'Source content is untrusted data. A webpage might contain instructions that try to redirect the answer system. Delimiting passages and telling the model to treat them as data is useful, but it is not a complete prompt-injection defense. Do not let retrieved instructions authorize tools, access secrets, or change system policy.' },
      { title: 'A missing answer is a real result.', text: 'Try the neural-network question with context enabled, then switch the evidence off. Without matching passages, our baseline refuses to manufacture an answer. That behavior is more useful than displaying a polished paragraph with nothing underneath it. Even with passages, an extractive selection can be incomplete or irrelevant, and a generative model can still make unsupported claims; the next lesson focuses on checking that connection.', detail: 'We use “not enough matching evidence” rather than claiming certainty about every possible answer. Search may fail even when useful information exists. A deployed system needs retrieval evaluation, calibrated refusal behavior, source-quality checks, and human review appropriate to its use.' }
    ],
    takeaway: 'Evidence should enter the system before an answer leaves it.',
    mission: ['Ask how neural networks learn and inspect the retrieved passages.', 'Open the assembled prompt and locate the source IDs.', 'Turn off context and compare the result with an unrelated query.'],
    bridge: 'Tomorrow, we make the source connection visible and check whether the evidence actually supports each claim.',
    codeTitle: 'Build an inspectable, extractive answer',
    code: `import { buildAnswer } from './src/engine.js';\n\nconst result = buildAnswer('how do neural networks learn?',\n  undefined, { k: 3, withContext: true });\n\nconsole.log(result.text);\nconsole.log(result.passages); // Exact sentences + offsets\nconsole.log(result.prompt);   // Context for a future LLM\n\n// No hidden network call. No text-generation model.\n// The baseline copies relevant source sentences.`,
    codeNote: 'The answer code runs locally. It never requires a secret in the browser and never describes a copied passage as live LLM output.',
    refs: ['rag'],
    quiz: [
      { q: 'What is the right order in this RAG pattern?', choices: ['Write an answer, then invent sources.', 'Retrieve evidence, supply context, then answer.', 'Discard all documents before asking a model.'], answer: 1, why: 'Retrieval provides the evidence the answer step should use.' },
      { q: 'What should happen when matching evidence is missing?', choices: ['Always guess confidently.', 'Reuse any citation number.', 'Clearly say the collection does not supply enough evidence.'], answer: 2, why: 'A refusal or limitation is more honest than fabricated content, though retrieval failure also needs investigation.' },
      { q: 'What creates the default answer in this course?', choices: ['A local extractive sentence selector.', 'A secret paid API call.', 'A newly trained frontier LLM.'], answer: 0, why: 'The course baseline is transparent and API-free. RAG generation is explained, not misrepresented as already connected.' }
    ]
  },
  {
    id: 6, name: 'Show the receipts', subtitle: 'A citation is a starting point, not proof.', color: 'blue', icon: 'link', time: '15–20 min', category: 'THE EVIDENCE',
    summary: 'Open source passages, audit claims, and catch a convincing-looking bad citation.',
    intro: 'Our system can now produce an answer from retrieved text, but how does the reader check where a particular claim came from? Today, let’s make the sources clickable and practice the important part: deciding whether a passage really supports the sentence beside its citation.',
    sections: [
      { title: 'Keep an address for each piece of evidence.', text: 'A document URL gets you to a page, but a passage ID and character offsets get you to the part the answer used. Our answer builder keeps that information together instead of trying to reconstruct it afterward. When the reader opens a source, the course shows the exact stored text. A simple validator can check that the document exists and that the cited text matches the stored slice.', detail: 'That validator checks provenance integrity, not factual truth or logical entailment. If a source itself is wrong, accurately quoting it does not fix it. If an answer adds an unsupported claim before a valid quotation, matching offsets will not detect that mistake.' },
      { title: 'Ask what the passage actually establishes.', text: 'In the audit lab, one claim is directly supported, another reverses what the source says, and a third makes a comparison the source never measured. Read the passage before choosing a verdict. The difference between “contradicted” and “not enough evidence” matters: absence of support is not automatically evidence of the opposite.', detail: 'A source about how to evaluate retrieval cannot establish that your project is faster than every commercial engine. A benchmark claim needs a defined test set, conditions, systems, dates, and measurements. Stronger wording needs stronger evidence.' },
      { title: 'Make uncertainty visible in the interface.', text: 'Citations should reduce the reader’s work, not decorate an answer. Keep them near the claim, make the source easy to inspect, and avoid implying that a check mark proves the whole answer is correct. In your production version, you might return structured claims and passage IDs, reject nonexistent references, and flag unsupported sentences for revision or review.', detail: 'Automatic support checks can help, but they can also be wrong. Independent verification matters more for higher-stakes uses. The exercise today uses authored answers and explanations so you can practice the reasoning without treating another model as a perfect judge.' }
    ],
    takeaway: 'Check the claim against the passage, not just the presence of a citation.',
    mission: ['Open each of the three source passages.', 'Mark each claim as supported, contradicted, or not enough evidence.', 'Explain why an existing source can still be a bad citation for a claim.'],
    bridge: 'For the final day, we stop judging by a single good demo and measure the whole search pipeline.',
    codeTitle: 'Check whether a quote belongs to a source',
    code: `function quoteBelongsToSource(passage, documents) {\n  const doc = documents.find(d => d.id === passage.docId);\n  if (!doc) return false;\n  return doc.body.slice(passage.start, passage.end)\n    === passage.text;\n}\n\n// This checks the stored quote, NOT the truth of a claim.\n// The full validator also checks offset bounds and types.`,
    codeNote: 'Inspect validateCitation() in src/engine.js. The audit lab uses human-authored support judgments, not an automatic fact-checking service.',
    refs: ['rag','ir'],
    quiz: [
      { q: 'The cited URL exists. What can we conclude?', choices: ['Every sentence in the answer is true.', 'The claim still needs to be checked against its source.', 'The source was read by a human.'], answer: 1, why: 'Existence alone establishes neither support nor truth.' },
      { q: 'A source never measures speed. A claim says our engine is fastest. The verdict is…', choices: ['Supported.', 'Automatically the opposite is true.', 'Not enough evidence from that source.'], answer: 2, why: 'The passage supplies no timing comparison. We should not invent either a positive or negative conclusion.' },
      { q: 'What do exact character offsets help us verify?', choices: ['Where the quoted text appears in the stored document.', 'That no source can ever change.', 'That every related claim is correct.'], answer: 0, why: 'Offsets let us reconstruct the evidence slice, while factual and logical support still require checking.' }
    ]
  },
  {
    id: 7, name: 'Put it to the test', subtitle: 'A good demo is not a benchmark.', color: 'lime', icon: 'flag', time: '20–25 min', category: 'THE FINISH LINE',
    summary: 'Compare three rankers, inspect relevance judgments, and export your actual results.',
    intro: 'For the last six days, we have improved one part of the system at a time. Now let’s find out which changes help across several questions rather than assuming the last version must be better. A test needs queries, a definition of a useful result, and measurements that we can reproduce.',
    sections: [
      { title: 'Decide what a good result looks like first.', text: 'Our benchmark includes exact searches, conversational rephrasings, a practical recipe question, and an out-of-collection query. Each one has an authored list of relevant document IDs that you can open before running the comparison. Those judgments are part of the experiment, not unquestionable truth. In a larger project, ask multiple reviewers to label results and document disagreements.', detail: 'This is a tiny, curated teaching benchmark over our local corpus. It is not a comparison against Google, Perplexity, or ChatGPT, and it should not be used to claim a commercial win. You can use the supplied comparison worksheet to record a separate, clearly dated manual test.' },
      { title: 'Look at more than one measurement.', text: 'Precision at three counts how many of the first three result slots are relevant and divides by three. Recall at three asks how many of the known relevant documents appear in those slots. Reciprocal rank gives 1 for a relevant result in first place, 1/2 for second, and so on; we average it across in-scope queries to get MRR. These measures tell different stories, so inspect the per-query results instead of only celebrating one average.', detail: 'Empty result slots count as nonrelevant for our P@3 convention. Queries with no relevant documents are excluded from relevance averages and get a separate abstention measurement. This demo’s MRR uses the full returned ranking, while precision and recall use the first three results. Timing is measured locally and excludes network/model downloads.' },
      { title: 'Change one thing, then compare again.', text: 'Run the keyword, teaching-vector, and hybrid rankers against exactly the same questions. Change the hybrid weight, rerun, and look for both improvements and regressions. Export the rows so the result of your experiment survives beyond the animation. If a change helps only the examples you used to tune it, you have learned something important about overfitting, not finished the evaluation.', detail: 'A production test also needs latency distributions, source coverage, freshness, cost, robustness, answer correctness, and citation support. Keep tuning queries separate from a held-out evaluation set. This course measures retrieval; it does not benchmark a language model’s answer quality.' }
    ],
    takeaway: 'Measure the behavior you care about, and be specific about what your test does not show.',
    mission: ['Inspect a relevance judgment, then run all three rankers.', 'Change the hybrid weight and find one query whose result changes.', 'Export the CSV, finish your checks, and save your builder notes.'],
    bridge: 'You now have an inspectable search pipeline and a method for improving it. The next step is replacing the teaching components one at a time, while keeping your tests.',
    codeTitle: 'Make a test you can run again',
    code: `import { benchmark } from './src/engine.js';\n\nconst report = benchmark(0.5);\nfor (const result of report) {\n  console.log(result.mode, {\n    precisionAt3: result.precision,\n    recallAt3: result.recall,\n    meanReciprocalRank: result.mrr,\n    outOfCollectionAbstention: result.abstention\n  });\n}\n\n// Same queries. Same corpus. Different ranking method.`,
    codeNote: 'Judgments live in src/data.js and metric definitions live in src/engine.js. tests/engine.test.mjs includes hand-calculated metric checks.',
    refs: ['metrics','ir'],
    quiz: [
      { q: 'Two of the first three result slots are relevant. P@3 is…', choices: ['2/3.', '3/2.', 'Exactly 1.'], answer: 0, why: 'Relevant items in the first three slots divided by three gives 2/3.' },
      { q: 'The first relevant result appears in position 4. Reciprocal rank is…', choices: ['4.', '0.25.', '0.75.'], answer: 1, why: 'Reciprocal rank is 1 divided by the position of the first relevant result.' },
      { q: 'Our hybrid ranker wins on these eight examples. What is a fair conclusion?', choices: ['It beats every commercial engine.', 'We never need to test again.', 'It performed better on this specific teaching test, if the measurements show that.'], answer: 2, why: 'A small local result supports a small local conclusion, not a universal product claim.' }
    ]
  }
];
export const GLOSSARY = [
  ['Query','The words or question someone gives the search engine.','Try the same idea with different wording.'],
  ['Corpus','The collection of documents available to search.','A search engine cannot retrieve a page that is missing from its corpus.'],
  ['Token','A unit produced when text is split for processing.','In Day 1 our tokens are lowercase words; LLM tokenizers can split text differently.'],
  ['Stopword','A common word optionally removed before matching.','Removing “how” and “do” can make the neural-network example more focused.'],
  ['Embedding','A numerical representation, often learned, of an item such as text.','The default lab uses explicitly hand-written concept coordinates, not neural inference.'],
  ['Cosine similarity','A measure of how closely two nonzero vectors point in the same direction.','A similarity score is not a probability that an answer is correct.'],
  ['Hybrid search','Retrieval that combines lexical and vector-based signals.','We normalize counts and mix them with teaching-vector similarity.'],
  ['Index','A stored representation of documents used for retrieval.','An index is not necessarily a live view of the web.'],
  ['Crawler','A program that discovers pages, commonly by following links.','Our Day 4 crawler explores a local website fixture, not the public web.'],
  ['RAG','Retrieval-augmented generation: supply retrieved evidence to an answer-generating model.','The default course demonstrates context assembly with an extractive answer baseline.'],
  ['Citation','A pointer from a claim to a source or passage.','A source can exist without supporting the claim.'],
  ['Precision@k','Relevant items in the first k result slots, divided by k.','In this course, empty slots count as nonrelevant.'],
  ['Recall@k','Known relevant items retrieved in the first k slots, divided by all known relevant items.','Depends on the completeness of your relevance judgments.'],
  ['MRR','Mean reciprocal rank: the average of 1 / first relevant position across queries.','For a query with no relevant result returned, its reciprocal rank is zero.'],
  ['Abstention','Declining to supply an answer or result when evidence is inadequate.','Refusing to invent an answer is useful; missing good evidence is still a retrieval problem.']
];
