import { DOCUMENTS, CONCEPTS, AUDIT, BENCHMARK, WEB_PAGES } from './data.js';
import { rank, teachingEmbedding, keywordDetails, buildAnswer, validateCitation, createCrawler, crawlStep, indexedDocuments, benchmark, tokenize } from './engine.js';
import { escapeHTML as e, icon, toast, openDialog, highlight, pct, download } from './ui.js';
import { state, markLab, save } from './store.js';

export function collection() {
  const extra = indexedDocuments(state.indexed).filter(d => !DOCUMENTS.some(x=>x.id===d.id));
  return [...DOCUMENTS,...extra];
}
const panel = (title, body, label = 'LIVE EXPERIMENT') => `<section class="panel"><div class="panel-head"><h3>${title}</h3><span class="eyebrow">${label}</span></div><div class="panel-body">${body}</div></section>`;
const notice = text => `<div class="notice">${icon('eye')}<p>${text}</p></div>`;
const tiny = text => `<p class="tiny-note">${text}</p>`;
function queryForm(value, suggestions, verb = 'Search') {
  return `<form class="search-form" id="lab-query-form"><label class="sr-only" for="lab-query">Your question</label><input id="lab-query" value="${e(value)}" maxlength="300" autocomplete="off" placeholder="Try a question…" required><button class="btn primary" type="submit">${icon('search')}${verb}</button></form><div class="suggestions">${suggestions.map(s=>`<button type="button" data-query="${e(s)}">${e(s)}</button>`).join('')}</div>`;
}
function onQueries(root, run) {
  const form = root.querySelector('#lab-query-form');
  form.addEventListener('submit', ev=>{ev.preventDefault();run(root.querySelector('#lab-query').value);});
  root.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{root.querySelector('#lab-query').value=b.dataset.query;form.requestSubmit();}));
}
function touch(day, onProgress) { const first=!state.labs.includes(day);markLab(day);onProgress?.();if(first) toast('Experiment tried! Your progress is saved.'); }
export function showDocument(id, docs = collection(), query = '', options = {}) {
  const d = docs.find(d=>d.id===id); if(!d)return;
  const detail = keywordDetails(query,d,options);
  openDialog(d.title,`<p class="result-url">${e(d.url)} · LOCAL TEACHING DOCUMENT</p><div class="source-document">${highlight(d.body,detail.terms)}</div>${query?`<h3 style="margin:23px 0 14px">Why did it match?</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Token</th><th>In title</th><th>In body</th></tr></thead><tbody>${detail.counts.map(c=>`<tr><td>${e(c.term)}</td><td>${c.title}</td><td>${c.body}</td></tr>`).join('')}</tbody></table></div><p style="margin-top:13px">Raw keyword score: ${detail.score}. These are exact occurrences, not a probability of relevance.</p>`:''}`);
}
function sourceListeners(root, docs, getQuery = ()=>'', getOptions = ()=>({})) {
  root.addEventListener('click',ev=>{const b=ev.target.closest('[data-doc]');if(b)showDocument(b.dataset.doc,docs,getQuery(),getOptions());});
}
export function resultsHTML(rows, { mode = 'keyword', alpha = .5, limit = 6, query = '', details = false } = {}) {
  if (!rows.length) return `<div class="empty-state">${icon('search')}<h3>No matching pages yet.</h3><p>${tokenize(query).length ? 'The collection or this representation cannot match that query. Try a different phrase, or inspect what is in the collection.' : 'Type a question with a few useful words to explore the collection.'}</p></div>`;
  return `<div class="output-meta"><span>${rows.length} matching ${rows.length===1?'page':'pages'} · showing ${Math.min(rows.length,limit)}</span><span>${mode==='keyword'?'Exact word counts':mode==='semantic'?'Cosine similarity':mode==='rrf'?'Reciprocal rank fusion':'Weighted hybrid score'}</span></div><div class="result-list">${rows.slice(0,limit).map((r,i)=>`<article class="result" data-result-id="${e(r.doc.id)}" style="animation-delay:${i*25}ms"><div class="result-heading"><button class="result-title" data-doc="${e(r.doc.id)}">${highlight(r.doc.title,r.terms)}</button><span class="score-badge">${mode==='keyword'?r.score:mode==='rrf'?r.score.toFixed(4):r.score.toFixed(2)}</span></div><div class="result-url">${e(r.doc.url)}</div><p>${highlight(r.doc.body,r.terms)}</p>${details&&mode==='hybrid'?`<div class="contrib" aria-label="Keyword contribution ${(alpha*r.keywordNormalized).toFixed(2)}, semantic contribution ${((1-alpha)*r.semantic).toFixed(2)}"><span class="lex" style="width:${alpha*r.keywordNormalized*100}%"></span><span class="sem" style="width:${(1-alpha)*r.semantic*100}%"></span></div><div class="breakdown-key"><span>exact ${(alpha*r.keywordNormalized).toFixed(2)}</span><span>meaning ${((1-alpha)*r.semantic).toFixed(2)}</span></div>`:''}<div class="result-footer"><span>#${i+1}</span><span>${e(r.doc.topic||'Your document')}</span><button data-doc="${e(r.doc.id)}">Inspect page ${icon('external')}</button></div></article>`).join('')}</div>`;
}
function paintResults(container, rows, options) {
  const before = new Map([...container.querySelectorAll('[data-result-id]')].map(el=>[el.dataset.resultId,el.getBoundingClientRect().top]));
  container.innerHTML=resultsHTML(rows,options);
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)container.querySelectorAll('[data-result-id]').forEach(el=>{const prev=before.get(el.dataset.resultId);if(prev!==undefined){const delta=prev-el.getBoundingClientRect().top;if(Math.abs(delta)>3)el.animate([{transform:`translateY(${delta}px)`},{transform:'translateY(0)'}],{duration:300,easing:'ease-out'});}});
}
function collectionButton(root, docs) {
  root.querySelector('[data-collection]')?.addEventListener('click',()=>openDialog('Your tiny internet',`<p>${docs.length} original teaching documents. These .test URLs are local examples, not live search results.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Document ID</th><th>Title</th><th>Topic</th></tr></thead><tbody>${docs.map(d=>`<tr><td><code>${e(d.id)}</code></td><td>${e(d.title)}</td><td>${e(d.topic)}</td></tr>`).join('')}</tbody></table></div>`));
}
function keywordLab(root,onProgress) {
  let query='how do neural networks learn?';const docs=DOCUMENTS;
  root.innerHTML=`<div class="lab-title"><h2>A search engine you can count by hand.</h2><p>Change the query, inspect the highlights, and see how the scoring rule behaves.</p></div><div class="lab-grid"><div class="lab-controls">${panel('Ask your tiny internet',`${queryForm(query,['neural networks','how do computers learn','garlic pasta'])}<div class="field"><div class="range-top"><label for="title-weight">Title match weight</label><output id="title-value">1×</output></div><input id="title-weight" type="range" min="1" max="5" value="1" step="1"></div><label class="check-field"><input id="stopwords" type="checkbox" checked>Remove common words</label><button class="text-link" data-collection style="margin-top:20px">${icon('folder')}Open the collection</button>`)}${notice('One exact occurrence = one point at the default weight. No stemming, no phrase detection, no AI model. Click a result to count its matches.')}</div>${panel('The ranked results','<div id="query-tokens" class="token-tray"></div><div id="search-results" aria-live="polite"></div>','FOLLOW THE WORDS')}</div>`;
  const options=()=>({mode:'keyword',titleWeight:Number(root.querySelector('#title-weight').value),removeStopwords:root.querySelector('#stopwords').checked});
  const render=()=>{const op=options();root.querySelector('#query-tokens').innerHTML=keywordDetails(query,docs[0],op).terms.map(w=>`<span class="token">${e(w)}</span>`).join('');paintResults(root.querySelector('#search-results'),rank(query,docs,op),{...op,query});};
  onQueries(root,q=>{query=q;render();touch(1,onProgress);});
  root.querySelector('#title-weight').oninput=ev=>{root.querySelector('#title-value').textContent=`${ev.target.value}×`;render();touch(1,onProgress);};
  root.querySelector('#stopwords').onchange=()=>{render();touch(1,onProgress);};
  sourceListeners(root,docs,()=>query,options);collectionButton(root,docs);render();return ()=>{};
}
function vectorHTML(vector, neural = false) {
  return `<div class="vector-grid">${vector.slice(0,8).map((v,i)=>`<div class="vector-item"><span>${neural?`dim ${i+1}`:CONCEPTS[i].name}</span><strong>${v.toFixed(2)}</strong><div class="bar"><i style="width:${Math.abs(v)*100}%"></i></div></div>`).join('')}</div>`;
}
function scatterHTML(query) {
  const q=teachingEmbedding(query);
  const points=DOCUMENTS.map(d=>({id:d.id,v:teachingEmbedding(`${d.title} ${d.body}`)}));
  return `<svg class="scatter" viewBox="0 0 510 240" role="img" aria-label="Two-axis slice of the teaching vectors. Horizontal axis learning, vertical axis food. Ranking uses all eight dimensions."><path d="M48 15V202H485" stroke="#b5a5c4" fill="none"/><path d="M48 108H485M266 15V202" stroke="#e5dcee" stroke-dasharray="4 5" fill="none"/><text x="415" y="227">Learning →</text><text x="5" y="16">Food ↑</text>${points.map(p=>`<circle cx="${48+p.v[0]*420}" cy="${201-p.v[2]*180}" r="5" fill="#9f8abd" opacity=".65"><title>${e(p.id)}</title></circle>`).join('')}<circle class="query-dot" cx="${48+q[0]*420}" cy="${201-q[2]*180}" r="8"/><text x="${Math.min(438,60+q[0]*420)}" y="${Math.max(30,190-q[2]*180)}">query</text></svg>`;
}
function semanticLab(root,onProgress) {
  let query='how do computers learn', neural=false, alive=true, request=0;
  const docs=DOCUMENTS;
  root.innerHTML=`<div class="lab-title"><h2>Turn “what I mean” into coordinates.</h2><p>Explore an understandable toy space, or optionally load a pretrained model.</p></div><div class="lab-grid"><div class="lab-controls">${panel('Compare ideas',`${queryForm(query,['how do computers learn','something easy for dinner','orbital zirconium'])}<div class="field"><label>Representation</label><span class="pill" id="model-label">8-axis teaching model</span></div>${tiny('Default: a hand-written vocabulary grouped into eight concepts. It is not a trained neural model.')}<div class="field"><button id="load-neural" class="btn small light">${icon('download')}Load neural model</button><button id="use-teaching" class="text-link" hidden style="margin-top:14px">Use teaching mode</button>${tiny('Optional: downloads MiniLM files from Hugging Face and a pinned library from jsDelivr. Internet required. Text is processed in your browser, not sent to a hosted model.')}<p id="neural-status" class="neural-status" role="status"></p></div>`)}${notice('A high cosine score means similar vector directions, not a guaranteed answer. Unknown words can disappear in the teaching model.')}</div>${panel('Inside the query vector','<div id="vector-space"></div><div id="semantic-results" aria-live="polite"></div>','COMPARE THE GEOMETRY')}</div>`;
  async function render(){
    const current=++request;
    let extra={};
    try{
      if(neural){root.querySelector('#neural-status').textContent='Embedding query and documents locally…';const {neuralVectors}=await import('./neural.js');extra=await neuralVectors(query,docs);if(!alive||current!==request)return;root.querySelector('#neural-status').textContent='Neural inference complete · 384 dimensions';}
      const v=extra.queryVector||teachingEmbedding(query);
      root.querySelector('#vector-space').innerHTML=`${vectorHTML(v,neural)}${neural?tiny('First 8 of 384 learned coordinates. These do not have human-assigned topic labels.'):scatterHTML(query)+tiny('Only learning and food are pictured. All eight dimensions are used for cosine similarity. Overlapping dots are normal in this tiny representation.')}`;
      paintResults(root.querySelector('#semantic-results'),rank(query,docs,{mode:'semantic',...extra}),{mode:'semantic',query,limit:4});
    }catch(err){if(alive){root.querySelector('#neural-status').textContent=`Neural inference failed: ${err.message}. Switch to teaching mode to continue.`;}}
  }
  onQueries(root,q=>{query=q;render();touch(2,onProgress);});
  root.querySelector('#load-neural').onclick=async ev=>{
    const b=ev.currentTarget;b.disabled=true;const status=root.querySelector('#neural-status');status.textContent='Loading optional model. Your first download can take a little while…';
    try{const {loadNeural}=await import('./neural.js');await loadNeural(p=>{if(alive&&p.status==='progress')status.textContent=`Loading ${p.file||'model'} · ${Math.round(p.progress||0)}%`;});if(!alive)return;neural=true;root.querySelector('#model-label').textContent='MiniLM · pretrained neural vectors';root.querySelector('#use-teaching').hidden=false;b.textContent='Neural model loaded';await render();touch(2,onProgress);}
    catch(err){if(alive){status.textContent=`Could not load the model: ${err.message}. The teaching lab still works.`;b.disabled=false;}}
  };
  root.querySelector('#use-teaching').onclick=()=>{neural=false;request++;root.querySelector('#model-label').textContent='8-axis teaching model';root.querySelector('#use-teaching').hidden=true;const b=root.querySelector('#load-neural');b.disabled=false;b.innerHTML=`${icon('spark')}Use neural model`;root.querySelector('#neural-status').textContent='Back in the offline teaching space.';render();};
  sourceListeners(root,docs,()=>query);render();return ()=>{alive=false;request++;};
}
function hybridLab(root,onProgress) {
  let query='a shorter way to write a loop';const docs=DOCUMENTS;
  root.innerHTML=`<div class="lab-title"><h2>You get to decide what matters.</h2><p>The result bars show exactly how the two signals contribute to the final score.</p></div><div class="lab-grid"><div class="lab-controls">${panel('Mix your signals',`${queryForm(query,['Python list comprehension','a shorter way to write a loop','how do computers learn'])}<div class="field"><label for="fusion">Combination method</label><select id="fusion"><option value="hybrid">Normalized weighted sum</option><option value="rrf">Reciprocal rank fusion</option></select></div><div class="field" id="weight-field"><div class="range-top"><label for="alpha">Exact-word weight</label><output id="alpha-label">50%</output></div><input id="alpha" type="range" min="0" max="100" value="50"><div class="range-ends"><span>Meaning only</span><span>Exact only</span></div></div><div class="prompt-details"><code id="fusion-equation">0.50 × keyword + 0.50 × meaning</code></div>`)}${notice('Keyword counts are divided by the largest count for this query. Meaning uses the offline teaching vectors. Neither score measures truth.')}</div>${panel('Watch the order change','<div id="hybrid-results" aria-live="polite"></div>','A LITTLE LESS GUESSWORK')}</div>`;
  const render=()=>{const mode=root.querySelector('#fusion').value,alpha=Number(root.querySelector('#alpha').value)/100;root.querySelector('#alpha-label').textContent=pct(alpha);root.querySelector('#weight-field').hidden=mode==='rrf';root.querySelector('#fusion-equation').textContent=mode==='rrf'?'1/(60 + keyword rank) + 1/(60 + semantic rank)':`${alpha.toFixed(2)} × keyword + ${(1-alpha).toFixed(2)} × meaning`;paintResults(root.querySelector('#hybrid-results'),rank(query,docs,{mode,alpha}),{mode,alpha,details:true,query});};
  onQueries(root,q=>{query=q;render();touch(3,onProgress);});
  root.querySelector('#alpha').oninput=()=>{render();touch(3,onProgress);};root.querySelector('#fusion').onchange=()=>{render();touch(3,onProgress);};
  sourceListeners(root,docs,()=>query);render();return ()=>{};
}
function crawlerLab(root,onProgress) {
  let crawler=createCrawler(12),timer=null;
  root.innerHTML=`<div class="lab-title"><h2>Follow one link. Then another.</h2><p>Watch an actual queue-and-seen-set algorithm run against a local website simulation.</p></div>${notice('Local website simulation · no requests to the public web. Pink means blocked; mint means visited. The graph is a fixture, and its robots rule is a simple blocked-page flag.')}<div class="crawl-layout" style="margin-top:20px">${panel('Your mini web',`<div class="web-graph" id="web-graph"></div><div class="stat-row" id="crawl-stats"></div><div class="actions" style="margin-top:17px"><button class="btn primary small" id="crawl-step">${icon('arrow')}Step once</button><button class="btn light small" id="crawl-run">${icon('play')}Auto-run</button><button class="icon-btn" id="crawl-reset" aria-label="Reset crawler">${icon('reset')}</button></div><div class="field"><label for="crawl-limit">Maximum indexed documents</label><select id="crawl-limit">${[3,6,9,12].map(n=>`<option value="${n}" ${n===12?'selected':''}>${n} documents</option>`).join('')}</select>${tiny('Changing the limit starts a fresh crawl. The hub does not count as a document.')}</div><button class="btn accent small" id="crawl-use" style="margin-top:15px" disabled>${icon('check')}Use indexed pages</button>`,'NO MAGIC, JUST LINKS')}${panel('Queue & visit log',`<span class="eyebrow">NEXT IN LINE</span><div id="crawl-queue" class="queue"></div><div class="section-heading" style="margin-top:22px"><h3 style="font-size:.9rem">What just happened?</h3></div><div id="crawl-log" class="crawl-log" aria-live="polite"></div>`,'THE CRAWLER’S TO-DO LIST')}</div>`;
  const positions=[[50,12],[20,36],[50,36],[80,36],[12,62],[20,85],[37,62],[50,85],[62,62],[80,85],[87,62],[86,12]];
  const graphPages=WEB_PAGES;
  function paint(){
    const links=graphPages.flatMap((p,i)=>p.links.map(h=>{let target;try{target=new URL(h,p.url);target.hash='';}catch{return '';}const j=graphPages.findIndex(x=>x.url===target.href);return j<0?'':`<line x1="${positions[i][0]}%" y1="${positions[i][1]}%" x2="${positions[j][0]}%" y2="${positions[j][1]}%" stroke="#c7c0d4" stroke-width="1.3"/>`;})).join('');
    root.querySelector('#web-graph').innerHTML=`<svg aria-hidden="true">${links}</svg>${graphPages.map((p,i)=>{const visited=crawler.seen.includes(p.url),queued=crawler.queue.includes(p.url);return `<button class="web-node ${visited?(p.blocked?'blocked':'visited'):queued?'queued':''}" data-web="${i}" style="left:${positions[i][0]}%;top:${positions[i][1]}%">${e(new URL(p.url).pathname)}</button>`;}).join('')}`;
    root.querySelector('#crawl-stats').innerHTML=[['queued',crawler.queue.length],['seen',crawler.seen.length],['indexed',crawler.indexed.length]].map(([label,num])=>`<div class="stat"><strong>${num}</strong><small>${label}</small></div>`).join('');
    root.querySelector('#crawl-queue').innerHTML=crawler.queue.slice(0,8).map(u=>`<span>${e(new URL(u).host==='byte.test'?new URL(u).pathname:new URL(u).host)}</span>`).join('')+(crawler.queue.length>8?`<span>+${crawler.queue.length-8}</span>`:'')||'<span>Queue empty</span>';
    root.querySelector('#crawl-log').innerHTML=(crawler.done?'<div class="notice warm">Crawl finished. Reached the index limit or exhausted the queue.</div>':'')+crawler.log.slice(0,25).map(l=>`<div class="log-row"><span class="log-status">${e(l.status)}</span><strong>${e(l.url.replace('https://',''))}</strong><p>${e(l.detail)}</p></div>`).join('')||'<p class="tiny-note">Take a step to visit the hub and discover your first links.</p>';
    root.querySelector('#crawl-step').disabled=crawler.done;root.querySelector('#crawl-use').disabled=!crawler.indexed.length;
    root.querySelector('#crawl-run').disabled=crawler.done;root.querySelector('#crawl-run').innerHTML=`${icon(timer?'pause':'play')}${timer?'Pause':'Auto-run'}`;
  }
  const stop=()=>{clearInterval(timer);timer=null;};
  const step=()=>{crawler=crawlStep(crawler);if(crawler.done)stop();paint();touch(4,onProgress);};
  root.querySelector('#crawl-step').onclick=step;
  root.querySelector('#crawl-run').onclick=()=>{if(timer)stop();else timer=setInterval(step,420);paint();};
  const reset=()=>{stop();crawler=createCrawler(Number(root.querySelector('#crawl-limit').value));paint();};
  root.querySelector('#crawl-reset').onclick=reset;root.querySelector('#crawl-limit').onchange=reset;
  root.querySelector('#crawl-use').onclick=()=>{state.indexed=[...new Set([...state.indexed,...crawler.indexed])];save();toast(`${collection().length} documents now available in your playground.`);touch(4,onProgress);};
  root.querySelector('#web-graph').onclick=ev=>{const b=ev.target.closest('[data-web]');if(!b)return;const p=graphPages[Number(b.dataset.web)];openDialog(`Page: ${new URL(p.url).pathname}`,`<p>${e(p.url)} · local fixture</p><p>${p.blocked?'Blocked by this teaching fixture’s robots rule.':p.docId?`Document ID: ${e(p.docId)}`:'Hub page: links only.'}</p><h3>Outgoing links</h3><div class="source-document">${e(p.links.join('\n')||'(none)')}</div>`);};
  paint();return stop;
}
function answerLab(root,onProgress) {
  let query='how do neural networks learn?',result,runId=0,alive=true;
  const docs=collection();
  root.innerHTML=`<div class="lab-title"><h2>An answer with evidence underneath.</h2><p>Follow retrieval → passages → context → an extractive answer.</p></div><div class="lab-grid"><div class="lab-controls">${panel('Build the context',`${queryForm(query,['how do neural networks learn?','how does a crawler work?','orbital zirconium'],'Build answer')}<div class="field"><label for="retrieval-k">Retrieve this many documents</label><select id="retrieval-k">${[1,2,3,4,5].map(n=>`<option value="${n}" ${n===3?'selected':''}>${n} document${n>1?'s':''}</option>`).join('')}</select></div><label class="check-field"><input type="checkbox" checked id="with-context">Include retrieved evidence</label>${tiny(`${docs.length} local documents · 900-character evidence budget · up to 3 copied sentences`)}`)}${notice('Offline extractive baseline, not live LLM generation. The answer copies selected source sentences. Open the prompt to see what a generative model would receive.')}</div>${panel('The evidence trail',`<div class="pipeline"><span class="stage" data-stage="0">Retrieve</span>${icon('arrow')}<span class="stage" data-stage="1">Select</span>${icon('arrow')}<span class="stage" data-stage="2">Assemble</span></div><div id="answer-output" aria-live="polite"></div>`,'INSPECT EVERY STEP')}</div>`;
  function show(){
    root.querySelectorAll('[data-stage]').forEach(s=>s.classList.add('active'));
    root.querySelector('#answer-output').innerHTML=`<div class="answer-box"><h3>${result.abstained?'Not enough matching evidence':'Selected source sentences'}</h3>${result.abstained?`<p>${e(result.text)}</p>`:result.passages.map((p,i)=>`<p>${e(p.text)} <button class="cite" data-passage="${i}">[${i+1}]</button></p>`).join('')}</div><div class="evidence-list">${result.passages.map((p,i)=>`<div class="evidence-item"><button data-passage="${i}">${icon('link')} [${i+1}] ${e(p.title)}</button><p><code>${e(p.id)}</code> · offsets ${p.start}–${p.end} · quote ${validateCitation(p,docs)?'matches source':'needs checking'}</p></div>`).join('')}</div><details class="prompt-details"><summary>Open the assembled prompt</summary><pre>${e(result.prompt)}</pre></details>`;
  }
  function calculate(){return buildAnswer(query,docs,{k:Number(root.querySelector('#retrieval-k').value),withContext:root.querySelector('#with-context').checked});}
  const run=async q=>{query=q;const id=++runId;result=calculate();root.querySelectorAll('[data-stage]').forEach(s=>s.classList.remove('active'));root.querySelector('#answer-output').innerHTML='<p class="tiny-note">Revealing the pipeline steps… This animation is not a model latency measurement.</p>';for(let i=0;i<3;i++){await new Promise(r=>setTimeout(r,170));if(!alive||id!==runId)return;root.querySelector(`[data-stage="${i}"]`).classList.add('active');}show();touch(5,onProgress);};
  onQueries(root,run);root.querySelector('#retrieval-k').onchange=()=>run(root.querySelector('#lab-query').value);root.querySelector('#with-context').onchange=()=>run(root.querySelector('#lab-query').value);
  root.querySelector('#answer-output').onclick=ev=>{const b=ev.target.closest('[data-passage]');if(!b)return;const p=result.passages[Number(b.dataset.passage)],doc=docs.find(d=>d.id===p.docId);openDialog(p.title,`<p><code>${e(p.id)}</code> · ${e(p.url)} · teaching source</p><div class="source-document">${e(doc.body.slice(0,p.start))}<mark>${e(p.text)}</mark>${e(doc.body.slice(p.end))}</div><p style="margin-top:16px">This exact source slice matches the stored offsets. That checks provenance, not the truth or completeness of an answer.</p>`);};
  result=calculate();show();return ()=>{alive=false;runId++;};
}
function citationLab(root,onProgress) {
  const verdicts={supported:'Supported',contradicted:'Contradicted',insufficient:'Not enough evidence'};let answers={};
  root.innerHTML=`<div class="lab-title"><h2>Would you trust these three claims?</h2><p>Open each citation, read the source, and choose the verdict the passage actually supports.</p></div>${notice('These are authored practice claims and judgments, not automated fact-checking. A valid citation can still fail to support a sentence.')}<div class="audit-grid" style="margin-top:20px">${AUDIT.map((a,i)=>`<article class="audit-card"><span class="eyebrow">CLAIM 0${i+1}</span><blockquote>${e(a.claim)} <button class="cite" data-audit-source="${i}">[${i+1}] Read source</button></blockquote><div class="verdicts" role="group" aria-label="Verdict for claim ${i+1}">${Object.entries(verdicts).map(([v,label])=>`<button data-verdict="${v}" data-claim="${i}" aria-pressed="false">${label}</button>`).join('')}</div><div id="audit-reason-${i}" aria-live="polite"></div></article>`).join('')}</div><div id="audit-summary" style="margin-top:20px"></div>`;
  root.onclick=ev=>{
    const source=ev.target.closest('[data-audit-source]');
    if(source){const a=AUDIT[Number(source.dataset.auditSource)];showDocument(a.source,DOCUMENTS);touch(6,onProgress);return;}
    const b=ev.target.closest('[data-verdict]');if(!b)return;const i=Number(b.dataset.claim),a=AUDIT[i];answers[i]=b.dataset.verdict;
    root.querySelectorAll(`[data-claim="${i}"]`).forEach(x=>{x.classList.toggle('chosen',x===b);x.setAttribute('aria-pressed',String(x===b));});
    root.querySelector(`#audit-reason-${i}`).innerHTML=`<div class="audit-reason" style="background:${answers[i]===a.verdict?'#eef6e4':'#fff0e0'}"><strong>${answers[i]===a.verdict?'Yes — that is the supported verdict.':'Take another look at what the passage establishes.'}</strong><br>${e(a.why)}</div>`;
    const score=AUDIT.filter((a,i)=>answers[i]===a.verdict).length;
    root.querySelector('#audit-summary').innerHTML=`<div class="notice">${icon('check')}<p>${score}/3 claims correctly audited. ${score===3?'You checked the evidence rather than just the citation label.':'Open a source again whenever you need it.'}</p></div>`;touch(6,onProgress);
  };return ()=>{};
}
function benchmarkLab(root,onProgress) {
  let report=null,alpha=.5;
  root.innerHTML=`<div class="lab-title"><h2>Let the experiment do the talking.</h2><p>Same collection. Same judgments. Three different rankers.</p></div>${notice('Eight authored teaching queries, not a commercial benchmark. Relevance averages use the seven in-scope queries; abstention is measured separately on the out-of-collection query.')}<div class="panel" style="margin-top:20px"><div class="panel-body"><div class="actions"><button class="btn primary" id="run-benchmark">${icon('play')}Run the benchmark</button><button class="btn light" id="export-benchmark" disabled>${icon('download')}Export CSV</button><span class="small muted" id="benchmark-timing"></span></div><div class="field" style="max-width:420px"><div class="range-top"><label for="bench-alpha">Hybrid exact-word weight</label><output id="bench-alpha-value">50%</output></div><input type="range" min="0" max="100" value="50" id="bench-alpha"></div><div id="benchmark-results" aria-live="polite"></div></div></div><details class="prompt-details" open><summary>Inspect all queries and relevance judgments</summary><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Query</th><th>Type</th><th>Authored relevant IDs</th></tr></thead><tbody>${BENCHMARK.map(b=>`<tr><td>${e(b.query)}</td><td>${e(b.kind)}</td><td>${b.relevant.map(id=>`<button data-doc="${e(id)}">${e(id)}</button>`).join(', ')||'None in collection'}</td></tr>`).join('')}</tbody></table></div></details>${tiny('P@3 divides by three even when fewer results are returned. MRR uses the full returned ranking. Local timing excludes network/model downloads. Change src/data.js to test your own judgments; use a separate held-out set for evaluation.')}`;
  root.querySelector('#bench-alpha').oninput=ev=>{alpha=Number(ev.target.value)/100;root.querySelector('#bench-alpha-value').textContent=pct(alpha);if(report)root.querySelector('#benchmark-timing').textContent='Weight changed — rerun to update the results.';};
  root.querySelector('#run-benchmark').onclick=()=>{
    const start=performance.now();report=benchmark(alpha);const elapsed=performance.now()-start;
    root.querySelector('#benchmark-timing').textContent=`24 local searches · ${elapsed.toFixed(1)} ms · weight ${pct(alpha)}`;
    root.querySelector('#export-benchmark').disabled=false;
    const labels={keyword:'Exact words',semantic:'Teaching vectors',hybrid:'Hybrid'};
    root.querySelector('#benchmark-results').innerHTML=`<div class="bench-cards">${report.map((r,i)=>`<div class="bench-card ${['yellow','pink','lavender'][i]}" style="background:var(--tone)"><h3>${labels[r.mode]}</h3><div class="big-metric">${pct(r.precision)}</div><span class="small">Precision@3</span><dl><div><dt>Recall@3</dt><dd>${pct(r.recall)}</dd></div><div><dt>MRR</dt><dd>${r.mrr.toFixed(2)}</dd></div><div><dt>Abstention</dt><dd>${pct(r.abstention)}</dd></div></dl></div>`).join('')}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Query</th>${report.map(r=>`<th>${labels[r.mode]} · top 3</th>`).join('')}</tr></thead><tbody>${BENCHMARK.map((b,i)=>`<tr><td>${e(b.query)}</td>${report.map(r=>`<td>${r.rows[i].results.slice(0,3).map((id,j)=>`<div class="${b.relevant.includes(id)?'correct-hit':'miss-hit'}">${j+1}. ${e(id)}${b.relevant.includes(id)?' ✓':''}</div>`).join('')||'<span class="muted">No results</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${tiny('Green IDs match the authored relevance labels. Checkmarks mean “labeled relevant in this fixture”, not verified facts. Lower average precision can coexist with a good first result.')}`;
    touch(7,onProgress);
  };
  root.querySelector('#export-benchmark').onclick=()=>{if(!report)return;const cell=x=>`"${String(x).replaceAll('"','""')}"`;const lines=[['method','query','kind','relevant_ids','returned_ids','precision_at_3','recall_at_3','reciprocal_rank','abstained'].join(',')];for(const r of report)for(const row of r.rows)lines.push([r.mode,row.query,row.kind,row.relevant.join('|'),row.results.join('|'),row.precision,row.recall??'',row.reciprocalRank,row.abstained].map(cell).join(','));download('search-engine-benchmark.csv',lines.join('\n'),'text/csv;charset=utf-8');};
  sourceListeners(root,DOCUMENTS);return ()=>{};
}
export function mountLab(day,root,onProgress) {
  return [keywordLab,semanticLab,hybridLab,crawlerLab,answerLab,citationLab,benchmarkLab][day-1](root,onProgress);
}

export function mountPlayground(root) {
  let docs=collection(),query='how do neural networks learn?';
  root.innerHTML=`<div class="playground-header"><span class="eyebrow">YOUR ENGINE, ALL TOGETHER</span><h1>Go on. Break something.</h1><p>Try your own questions, compare the rankers, add a document, and inspect where each answer comes from. It all runs right here.</p></div><div class="panel"><div class="panel-body">${queryForm(query,['how do computers learn','a shorter way to write a loop','quick garlic dinner'])}<div class="play-toolbar"><div><label for="play-mode">Retrieval</label><select class="select" id="play-mode"><option value="keyword">Exact words</option><option value="semantic">Teaching vectors</option><option value="hybrid" selected>Hybrid</option><option value="rrf">Rank fusion</option></select></div><div><label for="play-alpha">Hybrid weight: <output id="play-alpha-label">50%</output> exact</label><input type="range" min="0" max="100" value="50" id="play-alpha"></div><div><button class="btn small light" id="play-answer">${icon('chat')}Build extractive answer</button></div><div><button class="btn small light" id="export-corpus">${icon('download')}Export collection</button></div></div>${tiny('Vector search uses the hand-written teaching representation. Answers copy retrieved sentences; no LLM or hidden API call. Your additional documents remain in this session unless you export them.')}<div id="play-answer-output" style="margin-top:15px"></div></div></div><div class="lab-grid" style="margin-top:20px"><div class="lab-controls">${panel('Add to your tiny internet',`<form class="add-doc-form" id="add-doc"><label for="doc-title">Page title</label><input id="doc-title" required maxlength="100" placeholder="Your very useful page"><label for="doc-body">Page text</label><textarea id="doc-body" required maxlength="4000" placeholder="Write something you wish the search engine knew…"></textarea><button type="submit" class="btn accent small">${icon('folder')}Add document</button></form>${tiny('This adds text locally; it does not publish or crawl a website. A custom page gets an example .test address.')}<div id="corpus-count" class="pill" style="margin-top:17px">${docs.length} documents</div>`)}${notice('Add a page that answers a question the engine misses. Rerun the query and check whether the change is in the collection, the representation, or the ranking.')}</div>${panel('Your results','<div id="play-results" aria-live="polite"></div>','TINKER AWAY')}</div>`;
  const opts=()=>({mode:root.querySelector('#play-mode').value,alpha:Number(root.querySelector('#play-alpha').value)/100});
  function render(){const o=opts();root.querySelector('#play-alpha-label').textContent=pct(o.alpha);paintResults(root.querySelector('#play-results'),rank(query,docs,o),{...o,query,details:true,limit:8});root.querySelector('#play-answer-output').innerHTML='';}
  onQueries(root,q=>{query=q;render();});root.querySelector('#play-mode').onchange=render;root.querySelector('#play-alpha').oninput=render;
  root.querySelector('#add-doc').onsubmit=ev=>{ev.preventDefault();const title=root.querySelector('#doc-title').value.trim(),body=root.querySelector('#doc-body').value.trim();if(!title||!body){toast('Add both a title and some page text.');return;}if(docs.length>=100){toast('This teaching playground is limited to 100 documents.');return;}const id=`custom-${Date.now()}-${docs.length}`;docs.push({id,title,body,topic:'Your document',url:`https://your-page.test/${id}`});root.querySelector('#add-doc').reset();root.querySelector('#corpus-count').textContent=`${docs.length} documents`;render();toast('Page added locally. Try searching for it.');};
  root.addEventListener('click',ev=>{const b=ev.target.closest('[data-doc]');if(b)showDocument(b.dataset.doc,docs,query,opts());});
  root.querySelector('#export-corpus').onclick=()=>download('search-engine-documents.json',JSON.stringify(docs,null,2),'application/json');
  root.querySelector('#play-answer').onclick=()=>{query=root.querySelector('#lab-query').value;const res=buildAnswer(query,docs,{alpha:opts().alpha});root.querySelector('#play-answer-output').innerHTML=`<div class="answer-box"><h3>Offline extractive answer · always uses hybrid retrieval</h3>${res.abstained?`<p>${e(res.text)}</p>`:res.passages.map(p=>`<p>${e(p.text)} <button class="cite" data-doc="${e(p.docId)}">${e(p.id)}</button></p>`).join('')}</div>`;};
  render();return ()=>{};
}
